#!/usr/bin/env python

import os

os.system('FILE=$HOME/.cache/wal/colors ; cp $FILE .')

file = open('colors','r')

content = file.readlines()

file.close()

os.system('rm colors')

colors = []

for i in content:
    colors.append(i)

main_colors = []

main_colors.append(colors[0])
main_colors.append(colors[len(colors)-1])

background = main_colors[0]
foreground = main_colors[1]

file = open('/home/chagu/.config/xmobar/background', 'w')
file.write(background)
file.close()

file = open('/home/chagu/.config/xmobar/foreground', 'w')
file.write(foreground)
file.close()

#-----------------------------------------------------------------------------------#
bgfile = open("/home/chagu/.config/xmobar/background", 'r')
bgcolor = bgfile.readlines()
bgfile.close()

fgfile = open("/home/chagu/.config/xmobar/foreground", 'r')
fgcolor = fgfile.readlines()
fgfile.close()

bgcolor = '"' + bgcolor[0].strip() + '"'
fgcolor = '"' + fgcolor[0].strip() + '"'

reading_file = open("/home/chagu/.config/xmobar/xmobarrc_default", "r")

new_file_content = ""
for line in reading_file:
    stripped_line = line.strip()
    new_line = stripped_line.replace("xmobar_bg", bgcolor)
    new_file_content += new_line+"\n"
reading_file.close()

writing_file = open("/home/chagu/.config/xmobar/half_way", "w")
writing_file.write(new_file_content)
writing_file.close()



reading_file = open("/home/chagu/.config/xmobar/half_way", "r")

new_file_content = ""
for line in reading_file:
    stripped_line = line.strip()
    new_line = stripped_line.replace("xmobar_fg", fgcolor)
    new_file_content += new_line +"\n"
reading_file.close()

writing_file = open("/home/chagu/.config/xmobar/xmobarrc", "w")
writing_file.write(new_file_content)
writing_file.close()

os.system("killall xmobar")
os.system("xmobar /home/chagu/.config/xmobar/xmobarrc")
