--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/chagu/media/pics/Wallpapers/00091.png"

-- Special
background="#130d13"
foreground="#c1c8e8"
cursor="#c1c8e8"

-- Colors
color0="#130d13"
color1="#528CD8"
color2="#718ED8"
color3="#7D97E4"
color4="#D292B4"
color5="#ABA5DC"
color6="#8198E3"
color7="#c1c8e8"
color8="#878ca2"
color9="#528CD8"
color10="#718ED8"
color11="#7D97E4"
color12="#D292B4"
color13="#ABA5DC"
color14="#8198E3"
color15="#c1c8e8"
